# .golangci.yml
run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - govet
    - gosimple
    - unused

issues:
  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0
